version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://api_user:api_password@db:5432/api_auth_db
      - JWT_SECRET_KEY=development-secret-key-change-in-production
      - INVENTORY_API_BASE_URL=https://inventoryapp.usbtopia.usbbog.edu.co
      - DEBUG=true
    depends_on:
      - db
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: api_auth_db
      POSTGRES_USER: api_user
      POSTGRES_PASSWORD: api_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U api_user -d api_auth_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: